# Generated by Django 6.0.3 on 2026-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
