# Generated by Django 6.0.3 on 2026-04-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_exam_exam_type_alter_exam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
