# Generated by Django 6.0.3 on 2026-04-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
    ]
