# Generated by Django 6.0.3 on 2026-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
