# Generated by Django 6.0.3 on 2026-04-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
